server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: delivery

  datasource:
    url: jdbc:mysql://localhost:3306/delivery_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL

# JWT Configuration
jwt:
  secret: ZGVsaXZlcnktYXBwLWp3dC1zZWNyZXQta2V5LTIwMjQtc3VwZXItc2VjcmV0
  expiration: 86400000 # 24 horas

# CORS
cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:3001
    - http://127.0.0.1:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    - PATCH

# Logging
logging:
  level:
    com.delivery: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

# File Upload
spring.servlet.multipart:
  max-file-size: 10MB
  max-request-size: 10MB
