server:
  port: 8085
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: delivery-api

  # CONFIGURAÇÃO MYSQL
  datasource:
    url: jdbc:mysql://localhost:3306/delivery_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo&useLegacyDatetimeCode=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5

  # CONFIGURAÇÃO JPA/HIBERNATE
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 25
          fetch_size: 50
        order_inserts: true
        order_updates: true
        jdbc.lob.non_contextual_creation: true
        connection:
          characterEncoding: utf8
          CharSet: utf8
          useUnicode: true
    open-in-view: false

  # CONFIGURAÇÃO DE UPLOAD
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  # CONFIGURAÇÃO DE CACHE
  cache:
    type: simple

  # CONFIGURAÇÃO DE TRANSAÇÕES
  transaction:
    default-timeout: 30

# CONFIGURAÇÃO JWT
jwt:
  secret: bXlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25BbmRWYWxpZGF0aW9uUHVycG9zZXM=
  expiration: 86400000

# CONFIGURAÇÃO DE LOGS
logging:
  level:
    root: INFO
    com.delivery: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/delivery-api.log
    max-size: 10MB
    max-history: 30

# CONFIGURAÇÃO DE VALIDAÇÃO
validation:
  enabled: true

# CONFIGURAÇÃO DO ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# CONFIGURAÇÕES CUSTOMIZADAS DA APLICAÇÃO
app:
  name: "Delivery API"
  version: "1.0.0"
  description: "Sistema de Delivery - API REST"
  upload:
    path: "./uploads"
    max-size: 10485760
  pagination:
    default-size: 20
    max-size: 100